-- Migration: 010_presupuestos.sql
-- Description: Create presupuestos and presupuestos_detalle tables with RLS

CREATE TABLE IF NOT EXISTS public.presupuestos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_por UUID REFERENCES auth.users(id) NOT NULL,
    cliente_id VARCHAR(50) REFERENCES public.clientes(codigo_cliente),
    total_usd NUMERIC NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'borrador',
    pdf_url TEXT,
    nota TEXT,
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.presupuestos_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presupuesto_id BIGINT REFERENCES public.presupuestos(id) ON DELETE CASCADE NOT NULL,
    codigo_producto VARCHAR(50) REFERENCES public.productos(codigo_interno) NOT NULL,
    descripcion TEXT NOT NULL,
    cantidad NUMERIC NOT NULL,
    precio_unitario NUMERIC NOT NULL,
    subtotal NUMERIC GENERATED ALWAYS AS (cantidad * precio_unitario) STORED
);

-- Enable RLS
ALTER TABLE public.presupuestos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.presupuestos_detalle ENABLE ROW LEVEL SECURITY;

-- Policies for presupuestos
CREATE POLICY "owner_all_presupuestos" ON public.presupuestos
    FOR ALL
    TO authenticated
    USING (creado_por = auth.uid())
    WITH CHECK (creado_por = auth.uid());

-- Policies for presupuestos_detalle
CREATE POLICY "owner_all_presupuestos_detalle" ON public.presupuestos_detalle
    FOR ALL
    TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.presupuestos p
            WHERE p.id = presupuestos_detalle.presupuesto_id
            AND p.creado_por = auth.uid()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.presupuestos p
            WHERE p.id = presupuestos_detalle.presupuesto_id
            AND p.creado_por = auth.uid()
        )
    );
